import type { Metadata } from "next";
import { Space_Grotesk, Lexend_Deca } from 'next/font/google';
import "./globals.css";

const space = Space_Grotesk({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lexend = Lexend_Deca({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space.variable} ${lexend.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
